"""Seed a large board via the API for performance measurement.

Follows the same test-admin bootstrap pattern as ui-tests/conftest.py:
creates the canonical test-admin (test-admin@localhost / TestAdmin123!) via
POST /api/auth/setup/admin if setup isn't complete yet, then logs in and
imports a synthetic board using the native AFT JSON import format
(POST /api/boards/import). This exercises a real import code path rather
than writing to the database directly.

Usage:
    python perf-tests/seed_board.py --columns 8 --cards-per-column 100
"""
import argparse
import io
import json
import sys

import requests

BASE_URL = "http://localhost"
TEST_ADMIN_EMAIL = "test-admin@localhost"
TEST_ADMIN_USERNAME = "test-admin"
TEST_ADMIN_PASSWORD = "TestAdmin123!"


def mirror_secure_cookies(session):
    """Mirror Secure-flagged cookies as non-secure for plain http://localhost."""
    if not BASE_URL.startswith("http://"):
        return
    for cookie in [c for c in session.cookies if c.secure]:
        cookie_path = cookie.path or "/"
        session.cookies.set(cookie.name, cookie.value, path=cookie_path, secure=False)


def ensure_admin_and_login():
    session = requests.Session()

    status = requests.get(f"{BASE_URL}/api/auth/setup/status", timeout=5).json()
    if not status.get("setup_complete", False):
        resp = requests.post(
            f"{BASE_URL}/api/auth/setup/admin",
            json={
                "email": TEST_ADMIN_EMAIL,
                "username": TEST_ADMIN_USERNAME,
                "password": TEST_ADMIN_PASSWORD,
                "display_name": "Test Admin",
            },
            timeout=10,
        )
        if resp.status_code not in (200, 201):
            print(f"Failed to create test-admin: {resp.status_code} {resp.text}", file=sys.stderr)
            sys.exit(1)
        print("Created test-admin via setup endpoint.")

    login_resp = session.post(
        f"{BASE_URL}/api/auth/login",
        json={"email": TEST_ADMIN_EMAIL, "password": TEST_ADMIN_PASSWORD},
        timeout=10,
    )
    if login_resp.status_code != 200:
        print(f"Login failed: {login_resp.status_code} {login_resp.text}", file=sys.stderr)
        sys.exit(1)
    mirror_secure_cookies(session)
    print("Logged in as test-admin.")
    return session


def build_export_payload(board_name, num_columns, cards_per_column, checklist_items_per_card, comments_per_card):
    """Build an aft-board native export payload with synthetic data.

    IDs are local to this payload (1-based per collection) — the import
    handler remaps them, it only needs internal referential consistency.
    """
    columns = []
    cards = []
    checklists = []
    comments = []

    card_id = 0
    checklist_id = 0
    comment_id = 0

    for col_idx in range(1, num_columns + 1):
        column_id = col_idx
        columns.append({
            "id": column_id,
            "name": f"Column {col_idx}",
            "order": col_idx - 1,
        })

        for card_idx in range(cards_per_column):
            card_id += 1
            description = (
                f"Synthetic seed card {card_id} for performance measurement. "
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod "
                "tempor incididunt ut labore et dolore magna aliqua."
            )
            cards.append({
                "id": card_id,
                "column_id": column_id,
                "title": f"Card {card_id} (col {col_idx})",
                "description": description,
                "order": card_idx,
                "archived": False,
                "done": False,
                "scheduled": False,
            })

            for item_idx in range(checklist_items_per_card):
                checklist_id += 1
                checklists.append({
                    "id": checklist_id,
                    "card_id": card_id,
                    "name": f"Checklist item {item_idx + 1} for card {card_id}",
                    "checked": item_idx % 2 == 0,
                    "order": item_idx,
                })

            for comment_idx in range(comments_per_card):
                comment_id += 1
                comments.append({
                    "id": comment_id,
                    "card_id": card_id,
                    "comment": (
                        f"Seed comment {comment_idx + 1} on card {card_id}. "
                        "Consequat duis aute irure dolor in reprehenderit in voluptate velit."
                    ),
                    "order": comment_idx,
                })

    return {
        "export": {
            "format": "aft-board",
            "format_version": "1.0",
        },
        "board": {
            "name": board_name,
            "description": "Synthetic board generated by perf-tests/seed_board.py for performance measurement.",
        },
        "board_settings": [],
        "columns": columns,
        "cards": cards,
        "card_secondary_assignees": [],
        "checklists": checklists,
        "comments": comments,
        "scheduled_cards": [],
    }


def import_board(session, payload):
    file_bytes = json.dumps(payload).encode("utf-8")
    files = {"file": ("seed_board.json", io.BytesIO(file_bytes), "application/json")}
    resp = session.post(f"{BASE_URL}/api/boards/import", files=files, timeout=60)
    if resp.status_code not in (200, 201):
        print(f"Import failed: {resp.status_code} {resp.text}", file=sys.stderr)
        sys.exit(1)
    return resp.json()


def seed(board_name, columns, cards_per_column, checklist_items_per_card, comments_per_card):
    """Programmatic entry point — returns (session, board_dict)."""
    session = ensure_admin_and_login()
    payload = build_export_payload(
        board_name, columns, cards_per_column, checklist_items_per_card, comments_per_card
    )
    result = import_board(session, payload)
    return session, result.get("board") or {}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--board-name", default="Perf Seed Board")
    parser.add_argument("--columns", type=int, default=8)
    parser.add_argument("--cards-per-column", type=int, default=100)
    parser.add_argument("--checklist-items-per-card", type=int, default=3)
    parser.add_argument("--comments-per-card", type=int, default=2)
    args = parser.parse_args()

    total_cards = args.columns * args.cards_per_column
    print(
        f"Building payload: {args.columns} columns x {args.cards_per_column} cards "
        f"= {total_cards} cards, {args.checklist_items_per_card} checklist items/card, "
        f"{args.comments_per_card} comments/card..."
    )

    _session, board = seed(
        args.board_name,
        args.columns,
        args.cards_per_column,
        args.checklist_items_per_card,
        args.comments_per_card,
    )
    print(f"Imported board id={board.get('id')} name={board.get('name')!r}")
    print(f"Open it at: {BASE_URL}/board.html?id={board.get('id')}")


if __name__ == "__main__":
    main()
